- name: install openshift local storage
  hosts: localhost
  become: no
  gather_facts: no
  vars_files:
    - /data/drives.yml
  tasks:
    - name: ensure project exists
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            labels:
              openshift.io/cluster-monitoring: "true"
            name: openshift-local-storage
          spec: {}

    - name: ensure operatorgroup exists
      k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1
          kind: OperatorGroup
          metadata:
            name: local-storage
            namespace: openshift-local-storage
          spec:
            targetNamespaces:
            - openshift-local-storage

    - name: ensure subscription exists
      k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: local-storage-operator
            namespace: openshift-local-storage
          spec:
            channel: "{{ lookup('ini', 'local_storage section=operators file=/app/versions.ini') }}"
            name: local-storage-operator
            source: redhat-operators
            sourceNamespace: openshift-marketplace
            installPlanApproval: "Automatic"

    - name: save clusterserviceversion object
      set_fact:
        k8s_obj:
          apiVersion: operators.coreos.com/v1alpha1
          kind: ClusterServiceVersion
          name: local-storage-operator*
          namepace: local-storage

    - name: wait for operator to become ready
      assert:
        that: "lookup('k8s', resource_definition=k8s_obj)[0].status.phase | default('error') == 'Succeeded'"
      register: op_lkp
      until: op_lkp is success
      retries: 60
      delay: 15

    - name: ensure storage nodes are labeled
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Node
          metadata:
            name: "{{ item }}"
            labels:
              cluster.ocs.openshift.io/openshift-storage: ""
      loop: "{{ cluster_nodes }}"
      when: "item in use_drives"

    - name: ensure non-storage nodes are not labeled
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Node
          metadata:
            name: "{{ item }}"
            labels:
              cluster.ocs.openshift.io/openshift-storage: null
      loop: "{{ cluster_nodes }}"
      when: "item not in use_drives"

    - name: create localvolume object
      k8s:
        state: present
        definition:
          apiVersion: local.storage.openshift.io/v1
          kind: LocalVolume
          metadata:
            name: local-block-{{ item.key.split('.')|first }}
            namespace: openshift-local-storage
          spec:
            nodeSelector:
              nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - "{{ item.key }}"
            storageClassDevices:
              - storageClassName: localblock
                volumeMode: Block
                devicePaths: "{{ item.value }}"
      loop: "{{ lookup('dict', use_drives) }}"
