- name: install nvidia gpu drivers
  hosts: localhost
  become: no
  gather_facts: no

  tasks:
    - name: ensure project exists
      k8s:
        state: present
        definition:
          apiVersion: project.openshift.io/v1
          kind: Project
          metadata:
            name: gpu-operator-resources
          spec:

    - name: ensure nfd subscription exists
      k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: "{{ lookup('ini', 'nfd_name' section=operators file=/app/versions.ini') }}"
            namespace: openshift-operators
          spec:
            channel: "{{ lookup('ini', 'nfd_channel' section=operators file=/app/versions.ini') }}"
            name: "{{ lookup('ini', 'nfd_name' section=operators file=/app/versions.ini') }}"
            source: "{{ lookup('ini', 'nfd_source' section=operators file=/app/versions.ini') }}"
            sourceNamespace: openshift-marketplace
            installPlanApproval: "Automatic"

    - name: wait for install to start
      pause:
        seconds: 30

    - name: lookup install plan
      set_fact:
        install_plan: |
          "{{ lookup('k8s',
                     api_version='operators.coreos.com/v1alpha1',
                     kind='Subscription',
                     resource=lookup('ini', 'nfd_name' section=operators file=/app/versions.ini'),
                     namespace='openshift-operators',
                     wantlist=True)[0].status.installplan.name  }}"
      register: ip_lkp
      until: ip_lkp is success
      retries: 60
      delay: 15

    - name: wait for install to complete
      assert:
        that: |
          "{{ lookup('k8s',
                     api_version='operators.coreos.com/v1alpha1',
                     kind='InstallPlan',
                     resource=install_plan,
                     namespace='openshift-operators',
                     wantlist=True)[0].status.phase | default('error') == 'Complete' }}"
      register: op_lkp
      until: op_lkp is success
      retries: 60
      delay: 15

    - name: ensure nvidia subscription exists
      k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: gpu-operator-certified
            namespace: openshift-operators
          spec:
            channel: "{{ lookup('ini', 'nvidia_channel section=operators file=/app/versions.ini') }}"
            name: "{{ lookup('ini', 'nvidia_name section=operators file=/app/versions.ini') }}"
            source: "{{ lookup('ini', 'nvidia_source section=operators file=/app/versions.ini') }}"
            sourceNamespace: openshift-marketplace
            installPlanApproval: "Automatic"

    - name: wait for install to start
      pause:
        seconds: 30

    - name: lookup install plan
      set_fact:
        install_plan: |
          "{{ lookup('k8s',
                     api_version='operators.coreos.com/v1alpha1',
                     kind='Subscription',
                     resource=lookup('ini', 'nvidia_name section=operators file=/app/versions.ini'),
                     namespace='openshift-operators',
                     wantlist=True)[0].status.installplan.name  }}"

    - name: wait for install to complete
      assert:
        that: |
          "{{ lookup('k8s',
                     api_version='operators.coreos.com/v1alpha1',
                     kind='InstallPlan',
                     resource=install_plan,
                     namespace='openshift-operators',
                     wantlist=True)[0].status.phase | default('error') == 'Complete' }}"
      register: op_lkp
      until: op_lkp is success
      retries: 60
      delay: 15

    - name: create nfd server
      k8s:
        state: present
        definition:
          apiVersion: nfd.openshift.io/v1alpha1
          kind: NodeFeatureDiscovery
          metadata:
            name: nfd-master-server
            namespace: gpu-operator-resources
          spec:
            namespace: openshift-nfd
      register: cp_install
      until: cp_install is success
      retries: 30
      delay: 15

    - name: create nvidia clusterpolicy
      k8s:
        state: present
        definition:
          apiVersion: nvidia.com/v1
          kind: ClusterPolicy
          metadata:
            name: gpu-clusterpolicy
            namespace: gpu-operator-resources
          spec:
            dcgmExporter:
              nodeSelector: {}
              imagePullSecrets: []
              resources: {}
              affinity: {}
              podSecurityContext: {}
              repository: nvcr.io/nvidia/k8s
              securityContext: {}
              version: 2.0.13-2.1.0-ubi8
              image: dcgm-exporter
              tolerations: []
            devicePlugin:
              nodeSelector: {}
              imagePullSecrets: []
              resources: {}
              affinity: {}
              podSecurityContext: {}
              repository: nvcr.io/nvidia
              securityContext: {}
              version: v0.7.0-ubi8
              image: k8s-device-plugin
              tolerations: []
            driver:
              nodeSelector: {}
              imagePullSecrets: []
              resources: {}
              affinity: {}
              podSecurityContext: {}
              repository: nvcr.io/nvidia
              securityContext: {}
              version: 450.80.02
              image: driver
              tolerations: []
            gfd:
              nodeSelector: {}
              imagePullSecrets: []
              resources: {}
              affinity: {}
              podSecurityContext: {}
              repository: nvcr.io/nvidia
              securityContext: {}
              version: v0.2.1
              image: gpu-feature-discovery
              tolerations: []
              migStrategy: none
              sleepInterval: 60s
            operator:
              defaultRuntime: crio
              deployGFD: true
              validator:
                image: cuda-sample
                imagePullSecrets: []
                repository: nvcr.io/nvidia/k8s
                version: vectoradd-cuda10.2-ubi8
            toolkit:
              nodeSelector: {}
              imagePullSecrets: []
              resources: {}
              affinity: {}
              podSecurityContext: {}
              repository: nvcr.io/nvidia/k8s
              securityContext: {}
              version: 1.3.0-ubi8
              image: container-toolkit
              tolerations: []
      register: cp_install
      until: cp_install is success
      retries: 30
      delay: 15
